//Macro con argumentos incompletos
fn prueba4_error() {
    println!("a", 10, );
}

fn main() {
    prueba4_error();
}
